disabled_rules:
  - trailing_whitespace
  - function_parameter_count
  - nesting
  - large_tuple
  - for_where

opt_in_rules:
  - empty_count
  - redundant_discardable_let
  - unused_optional_binding
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type

analyzer_rules:
  - unused_import
  - unused_declaration

line_length: 340

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 600
  error: 1000

identifier_name:
  min_length: 1
  max_length: 50
  allowed_symbols: ["_"]
  excluded:
    - id
    - to
    - cc
    - ok

custom_rules:
  no_force_unwrap:
    name: "No Force Unwrap"
    regex: '\?!|\.[!?]\('
    message: "Avoid force unwrapping"
    severity: error

excluded:
  - .build
  - .github
  - .githooks
  - Package.swift
